---
title: "Intelligence quotients"
subtitle: "converting subtests raw scores"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Convert WASI t-scores to IQ scores}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
devtools::load_all(".")
```

## Background


## WASI vs. WPPSI

## Subtests
### Verbal subtests
#### Vocabulary
#### Similarities

### Performance subtests
#### Matrices
#### Block

## Intelligence scores
### T-scores vs. Scaled scores
### Verbal and Performance scores
### Full scale IQ

## Conversion tables
All IQ tests are under proprietary licences, and so are the conversion tables used to convert raw in to T or scaled scores.
These tables cannot be publicly shared in any way.
At LCBC, we have taken the time to punch the conversion tables and store them locally and secure on our servers.
To be able to use the functions in this package, you will need such a table, and we cannot provide you with it unless you work for us. 

The tables we have are punched _as is_ in the tables that accompany the test materials.
First column is the name of the `Subtest` (all subtests should be in the same table), 
then comes `Age` (as in the book, for children as in the book `7:3` meaning 7 years and 3 months). 
The remaining column names should be the `Score` (as in the table), and the cell contents the raw scores.
For ranges, only add in the lowest number, the functions in this package will fill out the range when numbers are omitted.

## Using the `iq` functions

The `iq` functions are quite complex to use, as there is quite a lot og logistics that need to work for them scores to be derived from the raw data.
Firstly, since both T and Scaled scored require age for conversion, this has to be available, for every raw subtest score, there must be an accompanying age to do the conversion.
Secondly, to be able to do the conversion, a conversion table must be supplied, and must have the specifications described in the *Conversion tables* sections
Once you have converted raw to T or Scaled scores, they can be combined, and then they must be converted again using other tables (in the standard Conversion tables format). 
At minimum two separate tables are needed to go from raw to full-scale IQ. 

## References
